config/routes.rb
Rails.application.routes.draw do
  devise_for :employers
  get 'employers/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root "jobs#index"
  get 'employers/new', to: 'employers#new'
  post 'employers/new', to: 'employers#create'
  post 'jobs/new', to: 'jobs#create'
  resources :jobs
  get 'sign_up', to: 'registrations#new'
  post 'sign_up', to: 'registrations#create'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create', as: 'log_in'
  delete 'logout', to: 'sessions#destroy'
  get 'password', to: 'passwords#edit', as: 'edit_password'
  patch 'password', to: 'passwords#update'
  get 'password/reset', to: 'password_resets#new'
  post 'password/reset', to: 'password_resets#create'
  get 'password/reset/edit', to: 'password_resets#edit'
  patch 'password/reset/edit', to: 'password_resets#update'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
  class Current < ActiveSupport::CurrentAttributes
    # makes Current.user accessible in view files.
    attribute :user
  end

app/models/employer.rb
class Employer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/job.rb
class Job < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
   # adds virtual attributes for authentication
   has_secure_password
   # validates email
   validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/, message: 'Invalid email' }
   enum role: [:worker,:hunter]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :set_current_user
    def set_current_user
      # finds user with session data and stores it if present
      Current.user = User.find_by(id: session[:user_id]) if session[:user_id]
    end
    def require_user_logged_in!
      # allows only logged in user
      redirect_to sign_in_path, alert: 'You must be signed in' if Current.user.nil?
    end
end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
before_action :require_user_logged_in!, only: [:edit,:update,:new,:create,:destroy]
def index
    @jobs = Job.all
  end

  def show
    @job = Job.find(params[:id])
  end  

  def edit
    @job = Job.find(params[:id])
  end  

  def update
    @job = Job.find(params[:id])

    if @job.update(job_params)
      redirect_to @job
    else 
      render :edit 
    end     
  end

  def new  
    @job = Job.new
  end

  def create

    @job = Job.new(job_params)
    
    if @job.save
      redirect_to @job
    else
      render :new
    end  
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    redirect_to @job
  end  

  private
    def job_params
      params.require(:job).permit(:title,:description)
    end  
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new; end
  def create
    @user = User.find_by(email: params[:email])
    if @user.present?
      # send mail
      PasswordMailer.with(user: @user).reset.deliver_later
      # deliver_later is provided by ActiveJob
    end
    redirect_to root_path, notice: 'Please check your email to reset the password'
  end
    def edit
      # finds user with a valid token
      @user = User.find_signed!(params[:token], purpose: 'password_reset')
      rescue ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: 'Your token has expired. Please try again.'
    end
    def update
      # updates user's password
      @user = User.find_signed!(params[:token], purpose: 'password_reset')
      if @user.update(password_params)
        redirect_to sign_in_path, notice: 'Your password was reset successfully. Please sign in'
        else
        render :edit
      end
    end
    private
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
 # allows only logged in users
    before_action :require_user_logged_in!
    def edit; end
    def update
      # update user password
      if Current.user.update(password_params)
        redirect_to root_path, notice: 'Password Updated'
      else
        render :edit
      end
    end
    private
    def password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
# instantiates new user
    def new
      @user = User.new
    end
    def create
      @user = User.new(user_params)
      if @user.save
      # stores saved user id in a session
        session[:user_id] = @user.id
        redirect_to root_path, notice: 'Successfully created account'
      else
        render :new
      end
    end
    private
    def user_params
      # strong parameters
      params.require(:user).permit(:email, :name, :role, :password, :password_confirmation)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
 def new; end
    def create
      user = User.find_by(email: params[:email])
      # finds existing user, checks to see if user can be authenticated
      if user.present? && user.authenticate(params[:password])
      # sets up user.id sessions
        session[:user_id] = user.id
        redirect_to root_path, notice: 'Logged in successfully'
      else
        flash.now[:alert] = 'Invalid email or password'
        render :new
      end
    end
    def destroy
      # deletes user session
      session[:user_id] = nil
      redirect_to root_path, notice: 'Logged Out'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employers_helper.rb
module EmployersHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/employers/index.html.erb
<%= render 'layouts/registration' %>
<h1>Найти рабочих</h1>
<p><%= link_to 'Создать', new_job_path%> обьявление о работе</p>

app/views/employers/test.html.erb
hi

app/views/jobs/_form.html.erb
<%= form_with model: @job do |form| %>
	<div>
		<%= form.label :title %><br>
		<%= form.text_field :title %>
		<% jobs.errors.full_messages_for(:title).each do |message|%>
			<div><%= message %></div>
			<% end %>
	</div>	

	<div>
		<%= form.label :description %><br>
		<%= form.text_area :description %>
		<% jobs.errors.full_messages_for(:description).each do |message| %>
			<div><%= message %></div>
			<% end %>
	</div>	

	<div>
		<%= form.submit %>
	</div>
<% end %>		

app/views/jobs/edit.html.erb
<%= render 'layouts/registration' %>
<h1> Изменить обьявление о работе </h1>
<%= render "form", jobs: @job %>

app/views/jobs/index.html.erb
<%= render 'layouts/registration' %>
<h1>Обьявления о работе</h1>
<p><ul>	
<% @jobs.each do |job| %>
	<li><%= link_to job.title, job_path(job.id) %> </li>
<% end %>
<%= link_to 'создать новое обьявление', new_job_path%>	
</ul></p>

app/views/jobs/new.html.erb
  <h1>Создать новое обьявление о работе</h1>
  <%= form_with model: @job, url: new_job_path do |f| %>
    <p>
    <%= f.label 'title' %><br>
    <%= f.text_field :title %>
    </p>
    <p>
    <%= f.label 'description' %><br>
    <%= f.text_field :description %>
    </p>
    <p>
    <%= f.label 'rate_hour' %><br>
    <%= f.number_field :rate_hour %>
    </p>
    <p>
      <%= f.label 'workmans_count' %><br>
      <%= f.number_field :workmans_count %>
    </p>
    <p>
      <%= f.label 'contact' %> <br>
      <%= f.text_field :contact %>
    </p>
    <p>
      <%= f.label 'duration' %> <br>
      <%= f.number_field :duration %>
    </p>
    <p>
    <%= f.submit 'Создать' %>
    </p>
  <% end %>

app/views/jobs/show.html.erb
<%= render 'layouts/registration' %>
<h1><%= @job.title %></h1>

<p> <%= @job.description %> </p>

<ul>
	<li><%= link_to "Edit", edit_job_path(@job)%></li>
	<li><%= link_to "Destroy", job_path(@job),
								method: :delete,
								data: {confirm: "Уверены?"} %></li>
	<li><%= link_to "All", jobs_path%></li>								
</ul>	

app/views/layouts/_registration.html.erb
 <% if Current.user %>
    Logged in as: <%= Current.user.email %><br>
    <%= link_to 'Edit Password', edit_password_path %>
    <%= button_to 'Logout', logout_path, method: :delete %>
    <% else %>
    <%= link_to 'Sign Up', sign_up_path %>
    or
    <%= link_to 'Login', sign_in_path %>
  <% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Podrabotka</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/layouts/registration.html.erb
 <% content_for :registration do -%>
 <% if Current.user %>
    Logged in as: <%= Current.user.email %><br>
    <%= link_to 'Edit Password', edit_password_path %>
    <%= button_to 'Logout', logout_path, method: :delete %>
    <% else %>
    <%= link_to 'Sign Up', sign_up_path %>
    or
    <%= link_to 'Login', sign_in_path %>
  <% end %>
  <% end -%>

app/views/password_resets/edit.html.erb
<h1>Reset your password?</h1>
  <%= form_with model: @user, url: password_reset_edit_path(token: params[:token]) do |f| %>
    <p>
    <%= f.label 'password:' %><br />
    <%= f.password_field :password %>
    </p>
    <p>
    <%= f.label 'password_confirmation:' %><br />
    <%= f.password_field :password_confirmation %>
    </p>
    <p>
    <%= f.submit 'Reset Password' %>
    </p>
  <% end %>

app/views/password_resets/new.html.erb
Hi <%= params[:user].email %>
Someone requested a password reset.
Click the link above if you recognise the activity, link expires in 15 minutes
<%= password_reset_edit_url(token: @token) %>